name: Route AI Change Requests

on:
  issues:
    types: [opened, labeled]

jobs:
  notify-copilot:
    # Only run when ai-change-request label is present
    if: contains(github.event.issue.labels.*.name, 'ai-change-request')
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Comment with Copilot instructions
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## 🤖 GitHub Copilot - Please Implement

            @github-copilot This is an AI-generated change request. Please:

            1. **Review** the Expected Change and Screenshot above
            2. **Locate** the component using the provided selector
            3. **Implement** the changes according to acceptance criteria
            4. **Test** locally (ensure no regressions)
            5. **Open a PR** linking back to this issue (use `Fixes #${{ github.event.issue.number }}`)

            ### Implementation Notes
            - Use the selector hint: check for `data-ai-id` attributes first
            - If screenshot shows layout, preserve spacing and alignment
            - Run existing tests before submitting PR
            - Consider mobile/responsive implications

            ### When Done
            - Link PR to this issue
            - Add screenshots/preview to PR description
            - Request review from original requester if possible

            ---

            _Automated by Inline AI Workflow_

      - name: Add metadata labels
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['copilot-ready', 'enhancement']
            });

      - name: Log to Actions
        run: |
          echo "✅ Notified Copilot for issue #${{ github.event.issue.number }}"
          echo "📋 Issue URL: ${{ github.event.issue.html_url }}"

  create-implementation-branch:
    # Create a branch and add a helpful starter comment for manual implementation
    if: contains(github.event.issue.labels.*.name, 'ai-change-request')
    runs-on: ubuntu-latest
    needs: notify-copilot

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create implementation branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "fix/issue-${{ github.event.issue.number }}"
          git push -u origin "fix/issue-${{ github.event.issue.number }}"

      - name: Comment with implementation instructions
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = `fix/issue-${{ github.event.issue.number }}`;
            const branchUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/tree/${branchName}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### 🚀 Implementation Branch Created

            A branch has been created for this issue: [\`${branchName}\`](${branchUrl})

            #### Option 1: Use GitHub Copilot in VS Code
            \`\`\`bash
            git fetch
            git checkout ${branchName}
            \`\`\`

            Then in VS Code Copilot Chat:
            \`\`\`
            @workspace Implement the changes from issue #${{ github.event.issue.number }}
            \`\`\`

            #### Option 2: Use GitHub Copilot Workspace
            Visit: https://copilot-workspace.githubnext.com/${context.repo.owner}/${context.repo.repo}/issues/${{ github.event.issue.number }}

            #### Option 3: Manual Implementation
            Review the issue details above and implement directly on the \`${branchName}\` branch.

            ---

            When done, open a PR from \`${branchName}\` → \`main\` and it will automatically link to this issue.`
            });
